### ISSUE TITLE
about nfs30 test?could you tell how to test it?

### ISSUE THREAD

**Issue by zxyyxzz** [Little-Podi/GRM#4]
When I test the model on nfs30, the architecture of nfs30 downloaded from the official website is different from the requirement of the code, then I  reorganize the structures of the dataset as anno and sequence, however, I meet the error: the label in the txt file can not convert to float. 

My question is that should I reorganize the architecture of nfs30? or where can I download the NFS30 dataset with anno and sequence structures?

**Comment by Little-Podi** [comment]
Hi there, may I ask if you are downloading NfS directly from [here](http://ci2cv.net/nfs/index.html)? That's exactly what I did and the code would run smoothly if I remember it correctly. Maybe these two answers (https://github.com/visionml/pytracking/issues/211, https://github.com/visionml/pytracking/issues/377) can help you to solve your issue. If it doesn't work, I also found a newly opened issue (https://github.com/visionml/pytracking/issues/400) that mentions a similar question. Since the codebase is based on [PyTracking](https://github.com/visionml/pytracking), I think most instructions and solutions from them are probably suit for this project as well.

**Comment by WenRuiCai** [comment]
Hi, I have the same question, have you solved this?
